export type Receta = {
  slug: string;
  titulo: string;
  descripcion: string;
  categoria: "sopas" | "segundos" | "granos" | "otros" | "postres" | "acompañamientos";
  fecha: string;
  porciones?: string;
  tiempo?: string;
  ingredientes: string[];
  pasos: string[];
  notas?: string;
};

export const recetas: Receta[] = [
  // Recetas nuevas 2024
  {
    slug: "sopa-de-mote",
    titulo: "Sopa de Mote",
    descripcion: "Una sopa tradicional andina preparada con mote, chancho y hierbas frescas. Reconfortante y llena de sabor.",
    categoria: "sopas",
    fecha: "2024-03-27",
    porciones: "6-8 porciones",
    tiempo: "4-5 horas",
    ingredientes: [
      "Mote (remojado desde la noche anterior)",
      "1 patita de chancho",
      "Pollo o cordero al gusto",
      "Hierbabuena al gusto",
      "Cebollino al gusto",
      "Sal al gusto",
      "Agua suficiente",
    ],
    pasos: [
      "Remojar el mote desde la noche anterior. Escurrir antes de usar.",
      "Colocar el mote en una olla grande con suficiente agua.",
      "Cuando suelte el primer hervor, agregar la patita de chancho.",
      "Dejar hervir 3 a 4 horas, revolviendo y agregando agua caliente según sea necesario.",
      "Agregar el pollo o cordero y continuar la cocción.",
      "Finalmente añadir la hierbabuena, el cebollino y la sal.",
      "Servir caliente.",
    ],
    notas: "La sopa se puede servir de inmediato o recalentar al día siguiente, cuando los sabores están más integrados.",
  },
  {
    slug: "carapulcra",
    titulo: "Carapulcra",
    descripcion: "Plato tradicional limeño con papa seca y cerdo en una salsa rica y sabrosa con ají panca y chocolate.",
    categoria: "segundos",
    fecha: "2024-03-11",
    porciones: "4-6 porciones",
    tiempo: "24h remojo + 1 hora cocción",
    ingredientes: [
      "500 g de papa seca",
      "50 g de manteca",
      "400 g de panceta de cerdo",
      "1 cebolla roja grande",
      "1 cucharada de pasta de ajo",
      "2 cucharadas de ají panca molido",
      "1 cucharada de pasta de ají mirasol",
      "Pizca de comino molido",
      "20 g de maní molido",
      "3 clavos de olor",
      "10 g de chocolate",
    ],
    pasos: [
      "Remojar la papa seca 24 horas antes, luego escurrir y reservar.",
      "Cortar el cerdo en cubos medianos.",
      "Picar la cebolla en brunoise fino.",
      "Calentar la manteca, dorar bien los cubos de cerdo y retirar.",
      "En la misma grasa, saltear la cebolla a fuego medio con sal.",
      "Agregar la pasta de ají mirasol, las especias y la pasta de ajo; revolver bien.",
      "Devolver el cerdo a la olla y remover constantemente.",
      "Verter 3 tazas de caldo y añadir los clavos de olor.",
      "Incorporar las papas hidratadas y cocinar 15 minutos revolviendo para que no se pegue.",
      "Rectificar la sazón, añadir el maní molido y el chocolate; revolver hasta integrar.",
    ],
    notas: "Preparación clásica limeña. El chocolate da un toque especial al sabor final.",
  },
  {
    slug: "conejo-o-cuye",
    titulo: "Conejo o Cuye",
    descripcion: "Sopa tradicional con conejo o cuye cocido lentamente con verduras y hierbas, espesada con sémola o arroz.",
    categoria: "sopas",
    fecha: "2024-03-04",
    porciones: "Conejo: 4 porciones / Cuye: 2 porciones",
    tiempo: "45-60 minutos",
    ingredientes: [
      "1 conejo (4 porciones) o 1 cuye (2 porciones)",
      "1.5 litros de agua",
      "Sal al gusto",
      "Orégano generoso",
      "1 cebolla",
      "Apio",
      "Ajo",
      "Porro",
      "Nabo",
      "Sémola o arroz para espesar",
    ],
    pasos: [
      "Hervir el agua con sal.",
      "Agregar el conejo o cuye y dejar hervir 5-10 minutos.",
      "Incorporar las verduras (cebolla, apio, ajo, porro, nabo) y el orégano.",
      "Una vez que la carne y las verduras estén a medio cocer, retirar la carne.",
      "Añadir sémola o arroz al caldo para espesar.",
      "Devolver la carne y servir caliente.",
    ],
  },
  {
    slug: "higado-de-pollo-encebollado",
    titulo: "Hígado de Pollo Encebollado",
    descripcion: "Hígados de pollo marinados con ají panca y sillao, salteados con cebolla, ají amarillo y tomate. Se sirven con papas y arroz blanco.",
    categoria: "segundos",
    fecha: "2024-02-27",
    porciones: "2-3 porciones",
    tiempo: "1h 30min (incluye marinado)",
    ingredientes: [
      "Hígados de pollo",
      "Ajo al gusto",
      "Ají panca al gusto",
      "Orégano al gusto",
      "Vinagre tinto (opcional)",
      "Sillao (salsa de soya)",
      "Sal y pimienta al gusto",
      "Comino al gusto",
      "Papas",
      "1 cebolla",
      "1 ají amarillo",
      "1 tomate",
      "Aceite",
      "Agua",
      "Arroz blanco para acompañar",
    ],
    pasos: [
      "Mezclar el ajo, ají panca, orégano, vinagre tinto (opcional), sillao, sal, pimienta y comino al gusto.",
      "Agregar los hígados a la mezcla y marinar en refrigeradora por al menos 1 hora.",
      "Cocinar las papas y cortarlas en rodajas.",
      "Freír los hígados en aceite caliente hasta dorar; retirar y reservar.",
      "En el mismo sartén saltear la cebolla en plumas y el ají amarillo.",
      "Añadir el tomate picado y mezclar bien.",
      "Regresar los hígados al sartén, agregar un chorrito de agua y rectificar la sazón.",
      "Servir de inmediato con las papas cocidas y arroz blanco.",
    ],
    notas: "Servir de inmediato para que los hígados queden jugosos.",
  },
  {
    slug: "pachamanca-a-la-olla",
    titulo: "Pachamanca a la Olla",
    descripcion: "Versión en olla del tradicional plato peruano con carnes marinadas en huacatay, papas, camotes, maíz y habas.",
    categoria: "segundos",
    fecha: "2018-08-06",
    porciones: "6-8 porciones",
    tiempo: "2-3 horas",
    ingredientes: [
      "Huacatay, sal, pimienta, comino y perejil (para la marinada)",
      "Res, cordero, conejo o pollo al gusto",
      "Cebolla y ajo",
      "Papas",
      "Camotes",
      "Choclo",
      "Habas con vaina",
    ],
    pasos: [
      "Licuar el huacatay con sal, pimienta, comino y perejil.",
      "Marinar las carnes más duras (res, cordero) 2 horas; el pollo 1 hora.",
      "Saltear cebolla y ajo en la olla; añadir huacatay y hierbas frescas.",
      "Agregar papas, camotes y choclo.",
      "Colocar las carnes por tiempo de cocción: primero res, cordero, conejo; después el pollo.",
      "Incorporar las habas unos 30 minutos después de comenzar la cocción.",
      "Verter el líquido de la marinada y llevar a hervor.",
      "Cocinar a fuego medio hasta que todo esté tierno.",
    ],
    notas: "La clave está en el huacatay fresco y en el orden de incorporación de los ingredientes según su tiempo de cocción.",
  },
  {
    slug: "caldo-de-res",
    titulo: "Caldo de Res",
    descripcion: "Reconfortante caldo de res con verduras, papas y pasta. Se puede preparar en olla a presión o tradicional.",
    categoria: "sopas",
    fecha: "2017-09-19",
    porciones: "4-6 porciones",
    tiempo: "20 min (presión) / 45 min (tradicional)",
    ingredientes: [
      "200 g de res con hueso",
      "1.25 litros de agua",
      "Sal y orégano al gusto",
      "1 zanahoria (en cuartos)",
      "½ col pequeña",
      "Papas (en cuartos)",
      "Apio, porro, cebolla, ajo",
      "Albahaca (molida o entera)",
      "Arroz, fideos o trigo entero (puñado pequeño)",
    ],
    pasos: [
      "En olla a presión: mezclar todo, hervir 15 minutos y listo.",
      "Sin olla a presión: hervir la carne 20 minutos con ajo, cebolla, apio, porro y sal.",
      "Agregar la col, zanahoria, ají, papa y el trigo/fideos; continuar la cocción.",
      "Cuando esté casi listo, añadir la albahaca licuada o bien picada.",
      "Rectificar la sazón y servir caliente.",
    ],
  },
  {
    slug: "cuy",
    titulo: "Cuy",
    descripcion: "Preparación tradicional de cuy cocido en caldo aromático con verduras. Simple, nutritiva y llena de sabor andino.",
    categoria: "sopas",
    fecha: "2017-09-19",
    porciones: "2 porciones",
    tiempo: "45 min (o 10 min en olla a presión)",
    ingredientes: [
      "½ cuy",
      "1 litro de agua",
      "Orégano al gusto",
      "Sal al gusto",
      "Ají (pimiento) al gusto",
      "Ajo",
      "Zanahoria",
      "Papa",
      "½ cebolla",
      "Apio y porro",
    ],
    pasos: [
      "Llevar el agua a hervir.",
      "Agregar el cuy junto con la cebolla en cuartos, diente de ajo, zanahoria, apio, porro y ají.",
      "Dejar cocer 45 minutos a fuego medio.",
      "Añadir las papas cortadas al tamaño deseado y cocinar hasta que estén listas.",
      "Servir caliente.",
    ],
    notas: "En olla a presión se reduce el tiempo a solo 10 minutos.",
  },
  {
    slug: "aji-de-gallina",
    titulo: "Ají de Gallina",
    descripcion: "Clásico peruano de pollo desmenuzado en cremosa salsa de ají amarillo, pan remojado, leche y nueces.",
    categoria: "segundos",
    fecha: "2017-06-09",
    porciones: "4 porciones",
    tiempo: "45 minutos",
    ingredientes: [
      "1 pechuga de pollo o gallina",
      "1 taza de caldo de pollo",
      "Galletas de soda o pan remojado",
      "1 cebolla roja",
      "Ajo al gusto",
      "½ taza de ají amarillo licuado",
      "Leche descremada al gusto",
      "Nueces (opcional)",
      "Perejil picado",
      "Sal al gusto",
    ],
    pasos: [
      "Cocinar y desmenuzar el pollo.",
      "Licuar el caldo con las galletas o pan hasta obtener una mezcla suave.",
      "Saltear la cebolla y el ajo en una olla.",
      "Agregar el ají amarillo y cocinar hasta que burbujee.",
      "Incorporar el pollo desmenuzado y revolver.",
      "Añadir la mezcla de caldo con galletas y continuar revolviendo.",
      "Sazonar con sal.",
      "Agregar las nueces picadas y la leche; mezclar bien.",
      "Añadir el perejil picado y cocinar a fuego lento unos minutos más.",
    ],
    notas: "Se puede servir sobre arroz blanco y papas sancochadas, decorado con aceitunas y huevo duro.",
  },
  {
    slug: "sancochado-de-quinua",
    titulo: "Sancochado de Quínua",
    descripcion: "Plato sencillo y nutritivo de quínua cocida con saltado de ajo y porro, queso, leche y huevo.",
    categoria: "granos",
    fecha: "2017-06-09",
    porciones: "2-3 porciones",
    tiempo: "30 minutos",
    ingredientes: [
      "1 taza de quínua",
      "2 tazas de agua",
      "Porro o cebolla al gusto",
      "Queso fresco o parmesano",
      "Leche al gusto",
      "1 huevo",
      "Sal al gusto",
      "Aceite para freír",
    ],
    pasos: [
      "Sancochar la quínua en 2 tazas de agua hasta que esté tierna.",
      "Picar el porro o cebolla y saltear en aceite.",
      "Mezclar la quínua cocida con el saltado.",
      "Agregar la leche y el queso desmenuzado.",
      "Sazonar con sal.",
      "Incorporar el huevo y mezclar bien.",
      "Servir caliente.",
    ],
  },
  {
    slug: "huevos-pasados",
    titulo: "Huevos Pasados",
    descripcion: "Huevos preparados al baño maría sobre aceite de oliva. Técnica delicada para un resultado suave y cremoso.",
    categoria: "otros",
    fecha: "2017-06-09",
    porciones: "1 porción",
    tiempo: "10 minutos",
    ingredientes: [
      "2 huevos",
      "1 cucharada de aceite de oliva",
      "Sal y pimienta al gusto",
    ],
    pasos: [
      "Preparar un baño maría con agua caliente.",
      "Colocar un plato resistente al calor sobre el baño maría.",
      "Verter el aceite de oliva en el plato.",
      "Romper los huevos sobre el plato con el aceite.",
      "Sazonar con sal y pimienta.",
      "Cocinar hasta el punto de cocción deseado.",
    ],
    notas: "La técnica de baño maría permite una cocción suave y uniforme, ideal para quienes prefieren la yema líquida.",
  },
  {
    slug: "seco-de-pollo",
    titulo: "Seco de Pollo",
    descripcion: "Estofado tradicional peruano de pollo en salsa cremosa de cilantro con papas y verduras.",
    categoria: "segundos",
    fecha: "2013-11-29",
    ingredientes: [
      "Pechuga y muslos de pollo",
      "1 cebolla",
      "Ajo",
      "Cilantro fresco",
      "Agua",
      "Arvejas",
      "Papas",
      "Zanahoria",
      "Cubo Maggi",
      "Ajinomoto",
      "Sal",
      "Gengibre (kion)",
    ],
    pasos: [
      "Freír la cebolla picada, luego agregar el ajo.",
      "Licuar cilantro con agua y agregar al sartén.",
      "Cocinar hasta que evapore el líquido, debe quedar amarillento-verdoso.",
      "Agregar arvejas, papas, zanahoria y pollo.",
      "Colocar en capas: primero el pollo picado, luego muslos, luego verduras.",
      "Agregar agua solo hasta cubrir las papas.",
      "No revolver hasta el primer hervor, después revolver según sea necesario.",
    ],
  },
  {
    slug: "aguadito",
    titulo: "Aguadito",
    descripcion: "Sopa tradicional de pollo y arroz con hierbas frescas, verduras y especias peruanas.",
    categoria: "sopas",
    fecha: "2013-11-29",
    ingredientes: [
      "1 cebolla",
      "Ajo",
      "Pollo",
      "Arroz",
      "Zanahoria",
      "Arvejas",
      "Pimiento",
      "Cilantro fresco",
      "Espinaca",
      "Orégano",
      "Sal",
      "Sazonador",
      "Agua",
    ],
    pasos: [
      "Picar cebolla y ajo.",
      "Freír primero cebolla, luego ajo.",
      "Agregar agua.",
      "Incluir pollo, arroz, zanahoria, arvejas y pimiento.",
      "Esperar a que el arroz reiente.",
      "Sazonar con sal y sazonador.",
      "Cuando el pollo esté cocido, agregar mezcla licuada de cilantro, espinaca y orégano.",
      "Llevar a un hervor final y servir.",
    ],
  },
  {
    slug: "recetas-con-arroz",
    titulo: "Recetas con Arroz",
    descripcion: "Arroz cocido al estilo Ayala Monge con plátano bellaco y cerdo aderezado.",
    categoria: "granos",
    fecha: "2013-10-18",
    ingredientes: [
      "Arroz",
      "2 plátanos bellaco",
      "Carne de cerdo",
      "Vino",
      "Ajo",
      "Pimienta",
      "Marinada",
    ],
    pasos: [
      "Preparar arroz al estilo Ayala Monge.",
      "Cuando el arroz esté a medio cocer, colocar encima 2 trozos de plátano bellaco.",
      "Agregar carne de cerdo aderezada con vino, ajo y pimienta.",
      "Permitir que el arroz termine de cocer.",
      "Servir con la carne y plátano.",
    ],
  },
  {
    slug: "cebiche-de-pollo-pollo-naranja",
    titulo: "Cebiche de Pollo / Pollo a la Naranja",
    descripcion: "Dos variaciones de pollo: una versión ceviche con limón y otra con naranja, ambas con especias peruanas.",
    categoria: "segundos",
    fecha: "2013-10-18",
    ingredientes: [
      "Piezas de pollo",
      "1 cebolla",
      "Ajo",
      "Gengibre (kion)",
      "Cúrcuma (palillo)",
      "Ají amarillo",
      "Cerveza",
      "Limón o naranja",
    ],
    pasos: [
      "Preparar mezcla de sazón: cebolla, ajo, gengibre, cúrcuma y ají amarillo.",
      "Pasar piezas de pollo por agua, luego dorar en la mezcla de sazón.",
      "Dejar cocinar el pollo hasta que esté dorado y completamente cocido.",
      "Agregar cerveza y jugo de limón (o naranja para la variante).",
      "Incorporar la mezcla de cebolla.",
      "Para pollo a la naranja, simplemente sustituir limón por naranja.",
    ],
  },
  {
    slug: "pescado-al-horno",
    titulo: "Pescado al Horno",
    descripcion: "Pescado horneado acompañado de papas y cebolla asadas, sazonado con hierbas de Provenza.",
    categoria: "segundos",
    fecha: "2013-10-18",
    porciones: "2-3 porciones",
    tiempo: "40 minutos",
    ingredientes: [
      "3 papas medianas",
      "1 cebolla grande",
      "Pescado fresco",
      "Pimienta negra",
      "Hierbas de Provenza",
      "Aceite o mantequilla",
      "Sal",
    ],
    pasos: [
      "Pelar y cortar papas y cebolla en rodajas.",
      "Sazonar con pimienta negra.",
      "Colocar en horno precalentado a temperatura media (con elemento superior e inferior).",
      "Después de aproximadamente 20 minutos, cuando las verduras comiencen a cocer, agregar el pescado limpio.",
      "Sazonar el pescado con hierbas de Provenza.",
      "Usar un molde alargado para el pescado y un plato cuadrado para las papas.",
      "Cocinar hasta que todo esté listo.",
    ],
  },
  {
    slug: "arroz-con-pollo",
    titulo: "Arroz con Pollo",
    descripcion: "Plato tradicional con pollo y arroz en caldo aromático de cerveza, cilantro y espinaca.",
    categoria: "segundos",
    fecha: "2013-10-18",
    ingredientes: [
      "½ taza de arroz",
      "Piezas de pollo",
      "¼ taza de aceite",
      "1 cebolla",
      "2 dientes de ajo",
      "Cilantro fresco",
      "Espinaca cocida",
      "Pimiento",
      "Cerveza",
      "Arvejas",
      "Choclo",
      "Sal y pimienta",
    ],
    pasos: [
      "Sazonar pollo con sal y pimienta, freír en aceite hasta cocer. Retirar.",
      "En el mismo aceite, saltear cebolla, ajo, cilantro y espinaca a fuego lento.",
      "Devolver el pollo al sartén.",
      "Agregar cerveza y continuar cocinando.",
      "Retirar el pollo.",
      "Agregar arroz, arvejas y choclo.",
      "Cocinar hasta que el arroz esté esponjoso.",
      "Servir.",
    ],
  },
  {
    slug: "chicharrones-lula",
    titulo: "Chicharrones Lula",
    descripcion: "Carnes fritas lentamente en su propio jugo con hierbabuena, cebolla y especias.",
    categoria: "segundos",
    fecha: "2013-10-18",
    porciones: "Variable",
    tiempo: "45 minutos",
    ingredientes: [
      "Carne (cerdo o res)",
      "Agua",
      "Sal",
      "Pimienta",
      "Hierbabuena",
      "½ cebolla",
    ],
    pasos: [
      "Colocar la carne en una olla.",
      "Agregar un chorrito de agua, sal, pimienta, hierbabuena y media cebolla.",
      "Dejar sancochado hasta que el agua se consume completamente.",
      "Servir cuando esté dorado y crujiente.",
    ],
  },
  {
    slug: "chicharrones-mama",
    titulo: "Chicharrones Mamá",
    descripcion: "Chicharrones de cerdo crujientes sazonados con hierbabuena, método de cocción en seco.",
    categoria: "segundos",
    fecha: "2013-10-18",
    porciones: "Variable",
    tiempo: "30-45 minutos",
    ingredientes: [
      "Carne de cerdo",
      "Aceite",
      "Hierbabuena",
      "Sal",
    ],
    pasos: [
      "Lavar la carne de cerdo sin escurrirla completamente.",
      "Colocar en una olla y revolver constantemente.",
      "Agregar un chorrito de aceite y continuar revolviendo.",
      "Freír completamente hasta que el agua se evapore.",
      "Agregar hierbabuena para darle una textura crujiente como galleta.",
      "Servir caliente.",
    ],
  },
  {
    slug: "alfajores",
    titulo: "Alfajores",
    descripcion: "Galletas dulces tradicionales rellenas de dulce de leche, masa mantequilluda y crujiente.",
    categoria: "postres",
    fecha: "2013-10-18",
    tiempo: "45 minutos + horneado",
    ingredientes: [
      "1 kg de harina",
      "500 g de mantequilla",
      "500 ml de agua con sal",
      "750 g de azúcar",
      "Dulce de leche (manjar blanco)",
    ],
    pasos: [
      "Hacer una fuente con la harina en una superficie de trabajo.",
      "Crear un pozo en el centro.",
      "Agregar mantequilla derretida, agua con sal tibia y azúcar en el pozo.",
      "Amasar durante aproximadamente 20 minutos hasta lograr una masa homogénea.",
      "Usar harina adicional si es necesario para evitar pegajosidad.",
      "Estirar la masa y cortar círculos usando un vaso.",
      "Colocar en bandeja engrasada.",
      "Hornear a 240°C durante 15 minutos.",
      "Retirar del horno y rellenar con dulce de leche.",
      "Servir.",
    ],
  },
  {
    slug: "tallarines-rojos",
    titulo: "Tallarines Rojos",
    descripcion: "Pasta con salsa de tomate casera, carne y verduras, espolvoreada con queso.",
    categoria: "segundos",
    fecha: "2012-08-27",
    tiempo: "20-30 minutos",
    ingredientes: [
      "1 cebolla",
      "Ajo",
      "Zanahoria",
      "Hoja de laurel",
      "Carne o pollo",
      "½ taza de vino",
      "Pomarola (tomate triturado)",
      "Queso rallado",
      "Tallarines",
    ],
    pasos: [
      "Freír cebolla y ajo (en este orden) hasta que la cebolla esté transparente.",
      "Agregar zanahoria rallada y hoja de laurel.",
      "Lavar y agregar la carne o pollo.",
      "Verter ½ taza de vino y pomarola.",
      "Cocinar a fuego medio durante 5-10 minutos.",
      "Retirar del fuego.",
      "Espolvorear queso rallado encima.",
      "Servir sobre tallarines cocidos.",
    ],
  },
  {
    slug: "sisiliana",
    titulo: "Sisiliana",
    descripcion: "Verdura cocida versátil con múltiples usos: acompañamiento, salteado o relleno para fritos.",
    categoria: "acompañamientos",
    fecha: "2011-09-15",
    ingredientes: [
      "Verduras variadas",
      "Papas",
      "Queso",
      "Ajo",
      "Aceite",
      "Huevos",
      "Harina",
      "Polvo de hornear",
      "Brócoli",
      "Carne molida",
      "Cebolla",
      "Tomate",
    ],
    pasos: [
      "Versión básica: cocinar verduras picadas, escurrir, preparar aderezo con aceite y ajo, mezclar con verduras y queso rallado. Cocer papas aparte.",
      "Variante Lomo Saltado: preparar como base pero en lugar de papas, usar la sisiliana como acompañamiento principal.",
      "Versión con carne molida: saltear ajo, cebolla y tomate, agregar carne molida, cocinar con agua y sisiliana.",
      "Variante de Brócoli: cortar y cocinar brócoli, batir huevos con harina y sal, mezclar con agua y polvo de hornear, rebozar el brócoli y freír.",
    ],
  },
  {
    slug: "chupe-de-camarones",
    titulo: "Chupe de Camarones",
    descripcion: "Estofado de mariscos peruano con camarones, papas, choclo, leche y huevo.",
    categoria: "sopas",
    fecha: "2011-09-14",
    tiempo: "30-40 minutos",
    ingredientes: [
      "330 g de camarones",
      "300 g de papas amarillas tiernas",
      "1 choclo tierno",
      "Ajo",
      "Cebolla",
      "Tomate",
      "Arvejas",
      "Arroz",
      "4 tazas de agua hirviendo",
      "1 taza de leche",
      "Huevos",
      "Sal",
      "Pimienta",
      "Orégano",
    ],
    pasos: [
      "Freír los camarones, luego retirar y reservar.",
      "En el mismo aceite, saltear ajo y cebolla picados, luego agregar tomate.",
      "Verter el agua hirviendo con choclo, arvejas, papas y arroz.",
      "Cocinar hasta que las verduras y el arroz estén tiernos.",
      "Retirar del fuego y devolver los camarones a la olla.",
      "Sazonar con orégano, sal y pimienta.",
      "Devolver al fuego para cocinar los camarones.",
      "Agregar huevos y leche justo antes de servir.",
    ],
  },
  {
    slug: "pollo-al-mani",
    titulo: "Pollo al Maní",
    descripcion: "Pollo estofado en salsa de maní con especias peruanas, simple y delicioso.",
    categoria: "segundos",
    fecha: "2011-09-14",
    tiempo: "25-30 minutos",
    ingredientes: [
      "Ají panca",
      "Cebolla",
      "Ajo",
      "Sal",
      "Ajinomoto (MSG)",
      "Orégano",
      "Piezas de pollo",
      "3 cucharadas de maní molido",
      "Agua",
    ],
    pasos: [
      "Freír el pollo sazonado con sal para sellarlo.",
      "En el mismo aceite, preparar la mezcla de sazón (ají panca, cebolla, ajo, ajinomoto, orégano).",
      "Agregar piezas de pollo con algo de agua.",
      "Llevar a hervor.",
      "Agregar el maní molido cuando empiece a hervir.",
      "Simular durante 10 minutos hasta que esté cocido.",
      "Servir.",
    ],
  },
  {
    slug: "mondonguito",
    titulo: "Mondonguito",
    descripcion: "Menudencia de res cocida y salteada con verduras, servida con arroz y papas.",
    categoria: "segundos",
    fecha: "2011-09-14",
    tiempo: "30-45 minutos",
    ingredientes: [
      "Mondonguito (mondongo)",
      "Hierbabuena",
      "Ají amarillo",
      "Papas",
      "Arvejas",
      "Zanahorias",
      "Cebolla",
      "Ajo",
      "Ajinomoto",
      "Cúrcuma (palillo)",
      "Arroz",
    ],
    pasos: [
      "Hervir el mondongo con hierbabuena durante 20 minutos.",
      "Cocinar papas aparte y dejar enfriar.",
      "Cortar ají amarillo en tiras finas.",
      "Preparar arvejas y zanahorias en tiras.",
      "Una vez cocido el mondongo, cortarlo en trozos.",
      "Mezclar con cebolla, ají amarillo, ajo, zanahorias y arvejas.",
      "Saltear con ajinomoto y cúrcuma.",
      "Servir con arroz y papas cocidas.",
    ],
  },
  {
    slug: "hornazo",
    titulo: "Hornazo",
    descripcion: "Bizcocho dulce tradicional con aceite de oliva, anís y semillas de ajonjolí.",
    categoria: "postres",
    fecha: "2011-09-14",
    tiempo: "1 hora aproximadamente",
    ingredientes: [
      "1 vaso de aceite de oliva",
      "1 vaso de leche",
      "1 vaso de azúcar (preferentemente morena)",
      "3 vasos de harina",
      "1 paquete de polvo de hornear Real",
      "Canela molida",
      "Licor de anís",
      "Semillas de ajonjolí (sésamo)",
    ],
    pasos: [
      "Precalentar horno a 356°C (180°C) durante 30 minutos con elementos superior e inferior.",
      "Calentar el aceite y agregar anís y semillas de ajonjolí sin freírlos.",
      "Combinar todos los ingredientes en un tazón.",
      "Engrasar el molde para hornear, espolvorear con harina y remover el exceso.",
      "Verter la mezcla en el molde.",
      "Hornear durante 30 minutos hasta que esté listo.",
    ],
  },
  {
    slug: "recetas-de-quinua",
    titulo: "Recetas de Quínua",
    descripcion: "Colección de múltiples preparaciones tradicionales con quínua andina.",
    categoria: "granos",
    fecha: "2011-07-08",
    ingredientes: [
      "Quínua",
      "Agua",
      "Huevos",
      "Harina",
      "Sal",
      "Aceite",
      "Puerro",
      "Cebolla",
      "Mantequilla",
      "Queso",
      "Leche",
      "Yuca",
      "Queso para relleno",
    ],
    pasos: [
      "Sancochado de quínua: cocinar quínua en proporción 1:2 (quínua:agua), batir huevo con harina y sal, combinar con quínua, freír hasta dorar.",
      "Quínua con queso: cocinar quínua, saltear puerro o cebolla, combinar, agregar lechey queso, mezclar bien.",
      "Preparación al horno con huevo: cocinar quínua, preparar huevo batido con harina, combinar ingredientes, hornear.",
      "Puerros fritos: cortar en rodajas, freír suavemente en mantequilla o en aceite caliente hasta crujir.",
      "Croquetas de yuca: hervir yuca, amasar, formar bolas con relleno de queso, freír en aceite caliente.",
    ],
  },
];

export const categorias = {
  sopas: "Sopas",
  segundos: "Segundos",
  granos: "Granos",
  postres: "Postres",
  acompañamientos: "Acompañamientos",
  otros: "Otros",
} as const;

export function getRecetaBySlug(slug: string): Receta | undefined {
  return recetas.find((r) => r.slug === slug);
}

export function formatFecha(fecha: string): string {
  const date = new Date(fecha + "T00:00:00");
  return date.toLocaleDateString("es-PE", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}
